project:
  type: book

book:
  title: "Data Science with R"
  author: "Victor Coppin"
  date: "29/06/2025"
  chapters:
    - index.qmd
    
    - part: "R Basics : Introduction to Data Science"
      chapters:

        - Tidyverse.qmd
    
    - part: "ggplot2: Elegant Graphics for Data Analysis"
      chapters:
        - ggplot2-introduction.qmd

     
    - part: "Foundations of Statistical Analysis and Machine Learning"
      chapters:
        - FSML-introduction.qmd
        - FSML-MQE.qmd
        - Inverse_Transform_Sampling.qmd    


    - part: "Advanced Statistical Analysis and Machine Learning"
      chapters:
        - ASML-introduction.qmd    


    - part: "Time Series Analysis"
      chapters:
        - TimeSeries-introduction.qmd    


    - part: "Statistical Analysis of Massive and High Dimensional Data"
      chapters:
        - massive-data-introduction.qmd    


    - summary.qmd
    - references.qmd

format:
  html:
    theme:
      - cosmo

  pdf:
    documentclass: scrreprt
