project:
  type: book

bibliography: references.bib
cite-method: biblatex


book:
  title: "Data Science with R"
  author: "Victor Coppin"
  date: "29/06/2025"
  chapters:
    - index.qmd
    
    - part: "R Basics : Introduction to Data Science"
      chapters:

        - Tidyverse.qmd
        - data-exploration.qmd

    - part: "ggplot2: Elegant Graphics for Data Analysis"
      chapters:
        - ggplot2-introduction.qmd
        - Fist-Steps-in-ggplot2.qmd

     
    - part: "Foundations of Statistical Analysis and Machine Learning"
      chapters:
        - FSML-introduction.qmd
        - FSML-MQE.qmd
        - The_normal_distribution.qmd
        - Inverse_Transform_Sampling.qmd
        - Construction_of_estimators.qmd
        - Methods_of_Moments.qmd
        - Maximum_Likelihood_Estimation.qmd
        - Confidence_interval.qmd
        - Simple_Linear_Regression.qmd

    - part: "Advanced Statistical Analysis and Machine Learning"
      chapters:
        - ASML-introduction.qmd    


    - part: "Time Series Analysis"
      chapters:
        - TimeSeries-introduction.qmd    


    - part: "Statistical Analysis of Massive and High Dimensional Data"
      chapters:
        - massive-data-introduction.qmd    


    - summary.qmd
    - references.qmd


format:
  html:
    theme:
      - cosmo

  pdf:
    documentclass: scrreprt
